name: Deploy site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ secrets.REPO_NAME }}

      - name: Delete artifact via API
        if: always()
        run: |
          ARTIFACT_NAME="github-pages"
          RUN_ID=${{ github.run_id }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
      
          # Получаем ID артефакта
          ARTIFACT_ID=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts" \
            | jq -r ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")
      
          # Удаляем артефакт
          if [ -n "$ARTIFACT_ID" ]; then
            curl -X DELETE -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID"
            echo "Artifact $ARTIFACT_NAME deleted."
          else
            echo "Artifact $ARTIFACT_NAME not found."
          fi
