name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Минимизируем вывод Git
          quiet: true
          # Используем токен из Secrets вместо стандартного GITHUB_TOKEN
          token: ${{ secrets.REPO_TOKEN }}
          # Указываем репозиторий из Secrets (если нужно кастомное имя, иначе берется текущий)
          repository: ${{ secrets.REPO_NAME }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Delete artifact via API
        if: always()
        run: |
          ARTIFACT_NAME="github-pages"
          RUN_ID=${{ github.run_id }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
      
          # Получаем ID артефакта
          ARTIFACT_ID=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts" \
            | jq -r ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")
      
          # Удаляем артефакт
          if [ -n "$ARTIFACT_ID" ]; then
            curl -X DELETE -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID"
            echo "Artifact $ARTIFACT_NAME deleted."
          else
            echo "Artifact $ARTIFACT_NAME not found."
          fi
